# Generated by Django 3.1.7 on 2021-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forda', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('available', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='', max_length=5)),
                ('price', models.FloatField(default=1000.0)),
                ('discount', models.FloatField(default=1000.0)),
                ('category', models.CharField(choices=[('c', 'Cakes'), ('sn', 'Snacks'), ('sw', 'sweets')], default='', max_length=50)),
                ('recomended', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='', max_length=5)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
