# Generated by Django 3.1.7 on 2021-04-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forda', '0006_auto_20210406_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('c', 'Cakes'), ('sn', 'Snacks'), ('sw', 'Sweets')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
