# Generated by Django 3.1.7 on 2021-04-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forda', '0007_auto_20210406_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
