# Generated by Django 3.1.7 on 2021-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forda', '0008_remove_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ca', 'Cakes'), ('sn', 'Snacks'), ('sw', 'Sweets')], default='', max_length=50),
        ),
    ]
